# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid/CMakeFiles /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid/CMakeFiles /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/barte/Desktop/RejsSochacki/ProjektBartek/bulid/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named projekt

# Build rule for target.
projekt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projekt
.PHONY : projekt

# fast build rule for target.
projekt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekt.dir/build.make CMakeFiles/projekt.dir/build
.PHONY : projekt/fast

#=============================================================================
# Target rules for targets named KapitanStatku

# Build rule for target.
KapitanStatku: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KapitanStatku
.PHONY : KapitanStatku

# fast build rule for target.
KapitanStatku/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanStatku.dir/build.make CMakeFiles/KapitanStatku.dir/build
.PHONY : KapitanStatku/fast

#=============================================================================
# Target rules for targets named KapitanPortu

# Build rule for target.
KapitanPortu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KapitanPortu
.PHONY : KapitanPortu

# fast build rule for target.
KapitanPortu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanPortu.dir/build.make CMakeFiles/KapitanPortu.dir/build
.PHONY : KapitanPortu/fast

#=============================================================================
# Target rules for targets named Pasazer

# Build rule for target.
Pasazer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pasazer
.PHONY : Pasazer

# fast build rule for target.
Pasazer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pasazer.dir/build.make CMakeFiles/Pasazer.dir/build
.PHONY : Pasazer/fast

KapitanPortu.o: KapitanPortu.cpp.o
.PHONY : KapitanPortu.o

# target to build an object file
KapitanPortu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanPortu.dir/build.make CMakeFiles/KapitanPortu.dir/KapitanPortu.cpp.o
.PHONY : KapitanPortu.cpp.o

KapitanPortu.i: KapitanPortu.cpp.i
.PHONY : KapitanPortu.i

# target to preprocess a source file
KapitanPortu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanPortu.dir/build.make CMakeFiles/KapitanPortu.dir/KapitanPortu.cpp.i
.PHONY : KapitanPortu.cpp.i

KapitanPortu.s: KapitanPortu.cpp.s
.PHONY : KapitanPortu.s

# target to generate assembly for a file
KapitanPortu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanPortu.dir/build.make CMakeFiles/KapitanPortu.dir/KapitanPortu.cpp.s
.PHONY : KapitanPortu.cpp.s

KapitanStatku.o: KapitanStatku.cpp.o
.PHONY : KapitanStatku.o

# target to build an object file
KapitanStatku.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanStatku.dir/build.make CMakeFiles/KapitanStatku.dir/KapitanStatku.cpp.o
.PHONY : KapitanStatku.cpp.o

KapitanStatku.i: KapitanStatku.cpp.i
.PHONY : KapitanStatku.i

# target to preprocess a source file
KapitanStatku.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanStatku.dir/build.make CMakeFiles/KapitanStatku.dir/KapitanStatku.cpp.i
.PHONY : KapitanStatku.cpp.i

KapitanStatku.s: KapitanStatku.cpp.s
.PHONY : KapitanStatku.s

# target to generate assembly for a file
KapitanStatku.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KapitanStatku.dir/build.make CMakeFiles/KapitanStatku.dir/KapitanStatku.cpp.s
.PHONY : KapitanStatku.cpp.s

Pasazer.o: Pasazer.cpp.o
.PHONY : Pasazer.o

# target to build an object file
Pasazer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pasazer.dir/build.make CMakeFiles/Pasazer.dir/Pasazer.cpp.o
.PHONY : Pasazer.cpp.o

Pasazer.i: Pasazer.cpp.i
.PHONY : Pasazer.i

# target to preprocess a source file
Pasazer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pasazer.dir/build.make CMakeFiles/Pasazer.dir/Pasazer.cpp.i
.PHONY : Pasazer.cpp.i

Pasazer.s: Pasazer.cpp.s
.PHONY : Pasazer.s

# target to generate assembly for a file
Pasazer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pasazer.dir/build.make CMakeFiles/Pasazer.dir/Pasazer.cpp.s
.PHONY : Pasazer.cpp.s

common.o: common.cpp.o
.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i
.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s
.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/common.cpp.s
.PHONY : common.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekt.dir/build.make CMakeFiles/projekt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekt.dir/build.make CMakeFiles/projekt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekt.dir/build.make CMakeFiles/projekt.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... KapitanPortu"
	@echo "... KapitanStatku"
	@echo "... Pasazer"
	@echo "... common"
	@echo "... projekt"
	@echo "... KapitanPortu.o"
	@echo "... KapitanPortu.i"
	@echo "... KapitanPortu.s"
	@echo "... KapitanStatku.o"
	@echo "... KapitanStatku.i"
	@echo "... KapitanStatku.s"
	@echo "... Pasazer.o"
	@echo "... Pasazer.i"
	@echo "... Pasazer.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

